### ISSUE TITLE
About k in make_cicero_cds() 

### ISSUE THREAD

**Issue by chent5** [cole-trapnell-lab/cicero#11]
Hi,

Thanks a lot for developing this package. 

I used Cicero to detect co-accessibility for each cluster separately. The number of cells in each cluster are various, from >400 to 42. If I ran make_cicero_cds() by default (k=50), it didn't work for the clusters with limited number of cells. I tried different k values (eg. 30, 15, 10), and found the number of co-accessible pairs of sites (above the threshold 0.2) significantly decrease along with the decrease in the k values.

To make the results of co-accessible pairs comparable across different clusters, should I use the same k value for all the clusters, or use different k for different clusters: higher k for the clusters with a large number of cells, and lower k for the clusters with limited number of cells?

Thanks so much!

**Comment by hpliner** [comment]
Hello, the answer here is going to depend a bit on what you mean by 'comparable'. Off the bat, you're always going to have some difficulty comparing across different datasets with vastly different cell numbers, if only because with fewer cells, there will be less accessibility - and so less ability to find co-accessible pairs. If you wanted to directly compare presence/absence, you would likely need to downsample your larger clusters and then use the same k. You could potentially do more qualitative comparisons at specific loci without downsamples, depending on the question.

In future, please post questions to the cicero users group so that other people can more easily find them. https://groups.google.com/forum/#!forum/cicero-users
